import { useState } from 'react';
import { pedirLoteHorarios, type LoteHorarios, type ItemHorario } from '../../services/loteHorarios.service';
/** Montar dentro de planificación existente. Nunca inicia un envío al abrir. */
function FranjaCita({item,onGuardada}:{item:ItemHorario;onGuardada:()=>Promise<void>}) {
 const [inicio,setInicio]=useState(item.franja?.inicio || '');const [fin,setFin]=useState(item.franja?.fin || '');const [error,setError]=useState('');const [guardando,setGuardando]=useState(false);
 async function guardar(){setGuardando(true);setError('');try{await pedirLoteHorarios({accion:'franja',ordenId:item.ordenId,franja:{inicio,fin}});await onGuardada();}catch(e){setError(e instanceof Error ? e.message : 'No se pudo guardar.');}finally{setGuardando(false);}}
 return <div className="flex flex-wrap gap-2 items-center mt-2"><label className="text-sm">Llegada desde <input aria-label={`Llegada desde para ${item.clienteNombre}`} type="time" value={inicio} onChange={e=>setInicio(e.target.value)} className="border rounded p-1"/></label><label className="text-sm">hasta <input aria-label={`Llegada hasta para ${item.clienteNombre}`} type="time" value={fin} onChange={e=>setFin(e.target.value)} className="border rounded p-1"/></label><button type="button" disabled={guardando || !inicio || !fin} onClick={guardar} className="border rounded px-2 py-1 text-sm">Guardar franja</button>{error && <p role="alert" className="text-red-700 text-sm">{error}</p>}</div>;
}
export default function LoteHorariosManana() {
 const [lote,setLote]=useState<LoteHorarios|null>(null);
 const [error,setError]=useState(''); const [cargando,setCargando]=useState(false);
 const [equipo,setEquipo]=useState('Todos'); const [confirmado,setConfirmado]=useState(false);const [resultados,setResultados]=useState<Record<string,string>>({});
 async function preparar() { setConfirmado(false);setResultados({});setCargando(true);setError('');try {setLote(await pedirLoteHorarios({accion:'preparar'}));} catch(e) {setError(e instanceof Error ? e.message : 'No se pudo preparar.');}finally{setCargando(false);} }
 async function enviar() {if(!confirmado || !lote?.envioHabilitado)return;setCargando(true);setError('');try {for(const item of items.filter(i=>i.enviable && i.version && i.bloqueos.length===0 && !resultados[i.ordenId])) {const r=await pedirLoteHorarios({accion:'enviar',confirmado:true,ordenId:item.ordenId,version:item.version}) as unknown as {estado?:string};setResultados(prev=>({...prev,[item.ordenId]:r.estado || 'Revisar resultado'}));}}catch(e){setError(e instanceof Error ? e.message : 'No se pudo enviar.');}finally{setCargando(false);setConfirmado(false);}}
 const items=lote?.items.filter(i => equipo==='Todos' || i.equipoId===equipo) ?? [];
 return <section className="rounded-xl border border-slate-200 bg-white p-4 space-y-3" aria-label="Horarios del siguiente día laboral">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Horarios de mañana</h3><p className="text-sm text-slate-600">Revisar citas y franjas antes del envío empresarial.</p></div><button type="button" onClick={preparar} disabled={cargando} className="rounded-lg bg-blue-900 px-4 py-2 text-white disabled:opacity-50">{cargando?'Preparando…':'Preparar horarios'}</button></div>
  {error && <p role="alert" className="text-red-700">{error}</p>}
  {lote && <><div className="flex gap-3 items-center"><span>{lote.fecha} · {items.length} citas</span><select aria-label="Filtrar equipo" value={equipo} onChange={e=>setEquipo(e.target.value)} className="rounded border p-2"><option>Todos</option><option>A</option><option>B</option></select></div>
   <p role="status" className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{lote.motivo}</p>
   <ul className="divide-y">{items.map(i=><li key={i.ordenId} className="py-3"><div className="font-medium">{i.clienteNombre} · {i.equipoId || 'Sin equipo'}</div><div className="text-sm">{i.franja ? `${i.franja.inicio}–${i.franja.fin}` : 'Sin franja de llegada'}</div>{resultados[i.ordenId] && <p role="status" className="text-sm">{resultados[i.ordenId]}</p>}{i.respuestaHorario && <p className="text-sm font-medium">{i.respuestaHorario==='horario_modificado'?'Horario modificado · requiere nueva confirmación':i.respuestaHorario==='confirmada'?'Cita aceptada':i.respuestaHorario==='reagendamiento_solicitado'?'Reagendar · atención pendiente':'Cancelar cita · atención pendiente'}</p>}{i.editable && <FranjaCita item={i} onGuardada={preparar}/>}{i.bloqueos.length>0 && <p className="text-sm text-amber-800">{i.bloqueos.join(' · ')}</p>}</li>)}</ul>
   <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={confirmado} onChange={e=>setConfirmado(e.target.checked)} disabled={cargando || !lote.envioHabilitado}/>Revisé los horarios y autorizo este lote de mensajes individuales.</label><button type="button" onClick={enviar} disabled={cargando || !confirmado || !lote.envioHabilitado} className="rounded-lg bg-blue-900 px-4 py-2 text-white disabled:opacity-50">Enviar horarios · {items.filter(i=>i.enviable && i.version && !resultados[i.ordenId]).length} preparados</button>
  </>}
 </section>;
}
