import { useState } from 'react';
import { Link } from 'react-router-dom';
import { BarChart3, RefreshCw, MessageSquare, BookOpen } from 'lucide-react';
import { equipoApi } from '../services/equipoApi';
interface Resumen { periodo: string; parcial: boolean; consultadoEn: string; campanas: { id: string; nombre: string; gasto: string; moneda: string; impresiones: string; clics: string }[] }
export default function MarketingIntegrado() {
  const [data, setData] = useState<Resumen | null>(null);
  const [error, setError] = useState('');
  const [cargando, setCargando] = useState(false);
  async function cargar() { setCargando(true); setError(''); try { setData(await equipoApi<Resumen>('/api/marketing/resumen')); } catch (e) { setError((e as Error).message); } finally { setCargando(false); } }
  return <div className="max-w-6xl mx-auto p-4 md:p-8 space-y-6"><header><h1 className="text-2xl font-bold text-primary flex items-center gap-3"><BarChart3 />Marketing y seguimiento</h1><p className="text-gray-600 mt-2">Desde la consulta del cliente hasta la atención y el resultado del servicio.</p></header>
    <div className="grid md:grid-cols-3 gap-4">{[{ to: '/admin/inbox', icon: MessageSquare, titulo: 'Atender consultas', texto: 'Revisa mensajes de WhatsApp y prepara respuestas.' }, { to: '/admin/clientes', icon: BarChart3, titulo: 'Dar seguimiento', texto: 'Consulta el historial y las campañas de reactivación.' }, { to: '/admin/conocimiento', icon: BookOpen, titulo: 'Aprender del equipo', texto: 'Comparte procedimientos y revisa los conocimientos.' }].map(c => <Link key={c.to} to={c.to} className="rounded-2xl border bg-white p-5 shadow-sm hover:border-primary"><c.icon className="text-primary mb-3" /><h2 className="font-semibold">{c.titulo}</h2><p className="text-sm text-gray-600 mt-2">{c.texto}</p></Link>)}</div>
    <section className="bg-white border rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-lg font-semibold">Anuncios de Mister Service</h2><p className="text-sm text-gray-500">Cuenta 180693964677323 · últimos 30 días · consulta de solo lectura</p></div><button disabled={cargando} onClick={cargar} className="bg-primary text-white rounded-xl px-4 py-3 inline-flex gap-2 items-center"><RefreshCw size={18} className={cargando ? 'animate-spin' : ''} />{cargando ? 'Consultando…' : 'Consultar Meta'}</button></div>{error && <p role="alert" className="bg-amber-50 text-amber-900 p-4 rounded-xl mt-4">{error}</p>}{!data && !error && <p className="mt-6 text-gray-500">Consulta Meta para ver resultados reales. No se cambian presupuestos ni anuncios.</p>}{data && <><p className="text-xs text-gray-500 mt-4">Consulta: {new Date(data.consultadoEn).toLocaleString('es-DO')}{data.parcial ? ' · Vista parcial: primeras 100 campañas.' : ''}</p><div className="overflow-x-auto mt-4"><table className="w-full text-sm text-left"><thead><tr className="border-b text-gray-500"><th className="p-3">Campaña</th><th className="p-3">Inversión</th><th className="p-3">Impresiones</th><th className="p-3">Clics</th></tr></thead><tbody>{data.campanas.map(c => <tr key={c.id} className="border-b"><td className="p-3 font-medium">{c.nombre}</td><td className="p-3">{c.moneda} {Number(c.gasto).toLocaleString('es-DO')}</td><td className="p-3">{Number(c.impresiones).toLocaleString('es-DO')}</td><td className="p-3">{Number(c.clics).toLocaleString('es-DO')}</td></tr>)}</tbody></table>{data.campanas.length === 0 && <p className="py-6 text-gray-500">Meta no reportó campañas con resultados para este período.</p>}</div></>}</section>
    <p className="text-sm text-gray-500">Instagram y Messenger están pendientes de habilitación y pruebas dentro de este sistema. Los clics no equivalen a ventas: la atribución a órdenes y pagos necesita validación adicional.</p>
  </div>;
}
