// Solo emuladores: verifica rechazo incluso sin pasar por los botones del CRM.
import assert from 'node:assert/strict';
import { initializeApp as adminApp } from 'firebase-admin/app';
import { getFirestore as adminDb } from 'firebase-admin/firestore';
import { initializeApp } from 'firebase/app';
import { getAuth, connectAuthEmulator, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, connectFirestoreEmulator, doc, setDoc, updateDoc } from 'firebase/firestore';
process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8289';
const adb = adminDb(adminApp({ projectId: 'demo-mister-ensayo' }));
const app = initializeApp({ projectId: 'demo-mister-ensayo', apiKey: 'demo-local-only' });
const auth = getAuth(app); connectAuthEmulator(auth, 'http://127.0.0.1:9198', { disableWarnings: true });
const db = getFirestore(app); connectFirestoreEmulator(db, '127.0.0.1', 8289);
await signInWithEmailAndPassword(auth, 'coordinadora@ensayo.invalid', 'EnsayoLocal-2026!');
const id = `ensayo-reglas-revision-${Date.now()}`;
const orden = { crmGestion: true, precioFinal: 8000, estadoPago: 'completo', pagos: [{ monto: 8000, verificado: true }], tecnicoId: 'ensayo_tecnico', cierreServicio: { fotoUrl: 'ficticia' }, fase: 'trabajo_realizado' };
const ref = adb.collection('ordenes_servicio').doc(id);
await ref.set(orden);
await adb.collection('crm_ordenes').doc(id).set({ version: 0 });
async function rechaza(f: () => Promise<unknown>) { await assert.rejects(f, (e: any) => e.code === 'permission-denied'); }
await rechaza(() => setDoc(doc(db, 'facturas', id+'-sin-revision'), { ordenId: id, total: 8000 }));
await rechaza(() => updateDoc(doc(db, 'ordenes_servicio', id), { facturada: true }));
const revision = { estado: 'revisado', precioFinal: 8000, pagos: orden.pagos, tecnicoId: orden.tecnicoId, cierreServicio: orden.cierreServicio };
await adb.collection('crm_ordenes').doc(id).set({ revision });
await setDoc(doc(db, 'facturas', id+'-valida'), { ordenId: id, total: 8000 });
await ref.update({ precioFinal: 8500 });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-cambiada'), { ordenId: id, total: 8500 }));
await ref.update({ precioFinal: 8000, estadoPago: 'parcial' });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-saldo'), { ordenId: id, total: 8000 }));
await ref.update({ estadoPago: 'completo' });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-total'), { ordenId: id, total: 9000 }));
await ref.update({ tecnicoId: 'otro-tecnico' });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-tecnico'), { ordenId: id, total: 8000 }));
await ref.update({ tecnicoId: orden.tecnicoId, cierreServicio: { fotoUrl: 'modificada' } });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-cierre'), { ordenId: id, total: 8000 }));
await ref.update({ cierreServicio: orden.cierreServicio, pagos: [{ monto: 8000, verificado: false }] });
await rechaza(() => setDoc(doc(db, 'facturas', id+'-pago'), { ordenId: id, total: 8000 }));
await ref.update({ pagos: orden.pagos });
await signInWithEmailAndPassword(auth, 'operaria@ensayo.invalid', 'EnsayoLocal-2026!');
await rechaza(() => setDoc(doc(db, 'facturas', id+'-operaria'), { ordenId: id, total: 8000 }));
console.log('Reglas CRM: sin revision rechazado, cierre directo rechazado, revision valida aceptada, cambios y saldo rechazados.');
process.exit(0);
