import {beforeEach,expect,it,vi} from 'vitest';
import type {VercelRequest,VercelResponse} from '@vercel/node';
const m=vi.hoisted(()=>({rol:'tecnico',uid:'tec',datos:{} as Record<string,Record<string,unknown>>,writes:vi.fn()}));
vi.mock('../../api/_lib/accesoEquipo.js',()=>({ErrorAcceso:class extends Error {constructor(public status:number,s:string){super(s)}},accesoEquipo:async()=>({uid:m.uid,rol:m.rol,db:{doc:(p:string)=>({path:p,collection:(c:string)=>({doc:(id:string)=>({path:`${p}/${c}/${id}`})})}),collection:(p:string)=>({path:p}),runTransaction:async(f:(t:unknown)=>unknown)=>f({get:async(r:{path:string})=>r.path==='personal'?{docs:[{id:'legacy',data:()=>({uid:'tec',activo:true})}]}:{exists:!!m.datos[r.path],data:()=>m.datos[r.path]},create:(r:{path:string},d:Record<string,unknown>)=>{m.writes();m.datos[r.path]=d},update:(r:{path:string},d:Record<string,unknown>)=>{m.writes();m.datos[r.path]={...m.datos[r.path],...d}}})}})}));
import handler from '../../api/ordenes/piezas';
const foto='https://firebasestorage.googleapis.com/v0/b/example/o/foto';
const pieza={nombre:'Bomba',cantidad:1,costo:900,foto};
async function call(extra:Record<string,unknown>={},raw=false){const res={status:vi.fn().mockReturnThis(),json:vi.fn().mockReturnThis(),setHeader:vi.fn()};const body={accion:'enviar',ordenId:'o',propuestaId:'piezas_test',piezas:[pieza],...extra};await handler({method:'POST',body:raw?JSON.stringify(body):body} as VercelRequest,res as unknown as VercelResponse);return res;}
beforeEach(()=>{m.rol='tecnico';m.uid='tec';m.writes.mockClear();m.datos={'usuarios/tec':{rol:'tecnico',activo:true},'ordenes_servicio/o':{tecnicoId:'legacy',fase:'en_diagnostico',inicioChequeo:{}}};});
it('acepta técnico legacy asignado y body JSON; reintento idempotente',async()=>{expect((await call({},true)).status).toHaveBeenCalledWith(200);expect((await call()).status).toHaveBeenCalledWith(200);expect(m.writes).toHaveBeenCalledTimes(1)});
it.each([{...pieza,costoOficina:0},null,{...pieza,costo:-1},{...pieza,cantidad:0},{...pieza,foto:'javascript:alert(1)'}])('rechaza pieza inválida o costo oficina inyectado %s',async p=>{expect((await call({piezas:[p]})).status).toHaveBeenCalledWith(400);expect(m.writes).not.toHaveBeenCalled()});
it('técnico ajeno y orden cerrada bloqueados',async()=>{m.datos['ordenes_servicio/o'].tecnicoId='otro';expect((await call()).status).toHaveBeenCalledWith(403);m.datos['ordenes_servicio/o'].tecnicoId='legacy';m.datos['ordenes_servicio/o'].fase='cerrado';expect((await call()).status).toHaveBeenCalledWith(409)});
it('sólo coordinación revisa costos conservando originales e historial',async()=>{await call();expect((await call({accion:'revisar',costos:[1000],revisionEsperada:0})).status).toHaveBeenCalledWith(403);m.rol='coordinadora';m.datos['usuarios/tec'].rol='coordinadora';expect((await call({accion:'revisar',costos:[1000],revisionEsperada:0})).status).toHaveBeenCalledWith(200);expect(m.datos['ordenes_servicio/o/interno/piezas_test'].piezas).toEqual([{...pieza,costoOficina:1000}]);expect((await call({accion:'revisar',costos:[500],revisionEsperada:0})).status).toHaveBeenCalledWith(409)});
