import { useEffect,useRef,useState } from 'react';
import { leerDocumentoPersonal,subirDocumentoPersonal,type TipoDocumentoPersonal } from '../../services/documentosPersonal.service';
const documentos:{tipo:TipoDocumentoPersonal;nombre:string}[]=[{tipo:'foto',nombre:'Foto del empleado'},{tipo:'cedula',nombre:'Identificación o cédula'},{tipo:'licencia',nombre:'Licencia de conducir (opcional)'}];
function DocumentoPrivado({personalId,tipo,nombre}:{personalId:string;tipo:TipoDocumentoPersonal;nombre:string}){
 const [url,setUrl]=useState('');const [error,setError]=useState('');const [ocupado,setOcupado]=useState(false);const urlRef=useRef('');const montado=useRef(true);
 useEffect(()=>{montado.current=true;return()=>{montado.current=false;if(urlRef.current)URL.revokeObjectURL(urlRef.current);};},[]);
 async function ver(){setOcupado(true);setError('');try{const blob=await leerDocumentoPersonal(personalId,tipo);if(!montado.current)return;const nueva=URL.createObjectURL(blob);if(urlRef.current)URL.revokeObjectURL(urlRef.current);urlRef.current=nueva;setUrl(nueva);}catch(e){if(montado.current)setError(e instanceof Error ? e.message:'No se pudo abrir.');}finally{if(montado.current)setOcupado(false);}}
 async function subir(file:File){setOcupado(true);setError('');try{await subirDocumentoPersonal(personalId,tipo,file);await ver();}catch(e){if(montado.current)setError(e instanceof Error ? e.message:'No se pudo subir.');}finally{if(montado.current)setOcupado(false);}}
 return <div className="rounded-lg border border-slate-200 p-3 space-y-2"><h4 className="font-medium">{nombre}</h4>{url && <img src={url} alt={nombre} className="max-h-48 max-w-full rounded object-contain"/>}<div className="flex flex-wrap gap-3"><button type="button" disabled={ocupado} onClick={ver} className="border rounded px-3 py-2 text-sm">Ver documento privado</button><label className="text-sm">Subir imagen<input type="file" accept="image/jpeg,image/png,image/webp" disabled={ocupado} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void subir(f);}} className="block max-w-full mt-1"/></label></div>{ocupado && <p role="status" className="text-sm">Procesando…</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}</div>;
}
export default function PersonalDocumentosPrivados({personalId}:{personalId:string}){return <section className="space-y-3"><h3 className="font-semibold">Documentos privados</h3><p className="text-sm text-slate-600">JPG, PNG o WebP de hasta 2 MB. Acceso reservado a administración y coordinación autorizadas.</p><div className="grid gap-3 md:grid-cols-3">{documentos.map(d=><DocumentoPrivado key={`${personalId}:${d.tipo}`} personalId={personalId} {...d}/>)}</div></section>;}
