import {useEffect,useState} from 'react';
import {equipoApi} from '../../services/equipoApi';
import {formatMoneda} from '../../utils';
type Fila={id:string;personalId:string;nombre:string;rol:string;dia:string;entrada:string|null;tipo:string;sugerido:number;minutos:number;revision:null|{estado:string;monto:number;motivo:string;version:number;conImagen:boolean;liquidacionId:string|null}};
const etiquetas:Record<string,string>={tardanza:'Tardanza',sin_ponche:'Sin entrada: verificar ausencia',dia_en_curso:'Día en curso',feriado:'Feriado remunerado',descanso:'Domingo',a_tiempo:'A tiempo',futuro:'Fecha futura',calendario_pendiente:'Calendario de feriados pendiente'};
export default function RevisionAsistencia({desde,hasta,liquidacionId}:{desde:string;hasta:string;liquidacionId?:string}){
 const [abierto,setAbierto]=useState(false),[items,setItems]=useState<Fila[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[recarga,setRecarga]=useState(0),[persona,setPersona]=useState('');
 const [seleccion,setSeleccion]=useState<Fila|null>(null),[motivo,setMotivo]=useState(''),[monto,setMonto]=useState(''),[falta,setFalta]=useState(false),[imagen,setImagen]=useState(''),[ocupado,setOcupado]=useState(false),[mensaje,setMensaje]=useState(''),[verImagen,setVerImagen]=useState(''),[limite,setLimite]=useState(100);
 useEffect(()=>{setSeleccion(null);setVerImagen('');setLimite(100);},[desde,hasta,liquidacionId]);
 useEffect(()=>{if(!abierto)return;let activo=true;setLoading(true);setError('');equipoApi<{items:Fila[]}>(`/api/asistencia?desde=${encodeURIComponent(desde)}&hasta=${encodeURIComponent(hasta)}`).then(r=>{if(activo)setItems(r.items);}).catch(e=>{if(activo){setItems([]);setError(e.message);}}).finally(()=>{if(activo)setLoading(false);});return()=>{activo=false;};},[abierto,desde,hasta,recarga]);
 const elegir=(f:Fila)=>{setSeleccion(f);setMotivo(f.revision?.motivo||'');setMonto(String(f.revision?.monto??f.sugerido));setImagen('');setFalta(false);setMensaje('');setVerImagen('');};
 const guardar=async(accion:string)=>{if(!seleccion)return;setOcupado(true);setError('');try{await equipoApi('/api/asistencia',{accion,personalId:seleccion.personalId,dia:seleccion.dia,version:seleccion.revision?.version||0,motivo,monto:Number(monto),faltaConfirmada:falta,...(imagen?{imagen}:{})});setSeleccion(null);setRecarga(v=>v+1);setMensaje('Revisión guardada. Solo los descuentos aprobados se incorporan a la nómina al pulsar Aplicar.');}catch(e){setError((e as Error).message);}finally{setOcupado(false);}};
 const adjuntar=async(file?:File)=>{if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Selecciona una imagen JPG, PNG o WebP.');return;}if(file.size>500000){setError('La imagen debe pesar como máximo 500 KB.');return;}const reader=new FileReader();reader.onload=()=>setImagen(String(reader.result));reader.onerror=()=>setError('No se pudo leer la imagen.');reader.readAsDataURL(file);};
 const visibles=items.filter(f=>!persona||f.personalId===persona);
 return <section className="rounded-xl border bg-white p-4 space-y-3">
  <button type="button" className="min-h-11 text-left font-semibold" aria-expanded={abierto} onClick={()=>setAbierto(!abierto)}>Asistencia y descuentos · {abierto?'Ocultar':'Revisar'}</button>
  {abierto&&<><p className="text-sm text-gray-600">L–V 8:00–18:00 · Sábados 8:00–16:00 · Almuerzo flexible de una hora no remunerada. Tolerancia hasta 8:10; después, RD$100 antes de 9:00 o RD$200 desde 9:00. Falta completa confirmada: RD$618. Ningún importe se aplica sin aprobación.</p>
   <p className="text-xs text-gray-500">Feriados 2026 excluidos. Otros años requieren confirmar su calendario antes de aprobar. Las imágenes y motivos se reservan a administración y coordinación.</p>
   <div className="flex flex-wrap gap-2"><label className="text-sm">Empleado<select className="block min-h-11 border rounded px-2" value={persona} onChange={e=>{setPersona(e.target.value);setLimite(100);}}><option value="">Todos</option>{[...new Map(items.map(f=>[f.personalId,f.nombre]))].map(([id,nombre])=><option key={id} value={id}>{nombre}</option>)}</select></label><button className="min-h-11 px-3 underline" disabled={loading||ocupado} onClick={()=>setRecarga(v=>v+1)}>Actualizar</button></div>
   {error&&<p role="alert" className="text-red-700">{error}</p>}{mensaje&&<p role="status" className="text-green-700">{mensaje}</p>}
   {loading?<p role="status">Cargando asistencia…</p>:<div className="max-h-96 overflow-auto space-y-2">{visibles.slice(0,limite).map(f=><div key={f.id} className="border rounded-lg p-3 flex flex-wrap gap-2 items-center justify-between"><div className="text-sm"><strong>{f.nombre}</strong> · {f.dia}<p>{etiquetas[f.tipo]}{f.tipo==='tardanza'?` · ${f.minutos} minutos desde las 8:00`:''}</p><p>{f.revision?`${f.revision.estado} · ${formatMoneda(f.revision.monto)}`:`Propuesta: ${formatMoneda(f.sugerido)}`}{f.revision?.liquidacionId?' · Aplicada a nómina':''}</p></div><button className="min-h-11 border rounded px-3" onClick={()=>elegir(f)}>{f.revision?.liquidacionId?'Ver revisión':'Revisar / Excusar día'}</button></div>)}{visibles.length>limite&&<button className="min-h-11 underline" onClick={()=>setLimite(v=>v+100)}>Mostrar más días</button>}{!visibles.length&&!error&&<p>No hay registros para este rango.</p>}</div>}
   {seleccion&&<div className="rounded-xl border border-blue-300 p-4 space-y-3"><h3 className="font-semibold">{seleccion.nombre} · {seleccion.dia}</h3><p className="text-sm">{etiquetas[seleccion.tipo]} · Propuesta original {formatMoneda(seleccion.sugerido)}</p>
    <label className="block text-sm">Motivo obligatorio<textarea className="block w-full border rounded p-2" maxLength={1000} value={motivo} disabled={!!seleccion.revision?.liquidacionId||ocupado} onChange={e=>setMotivo(e.target.value)}/></label>
    <label className="block text-sm">Importe a aprobar (RD$)<input type="number" min="0" step="0.01" className="block border rounded p-2" value={monto} disabled={!!seleccion.revision?.liquidacionId||ocupado} onChange={e=>setMonto(e.target.value)}/></label>
    {seleccion.tipo==='sin_ponche'&&<label className="block text-sm"><input type="checkbox" checked={falta} onChange={e=>setFalta(e.target.checked)}/> Confirmo que faltó el día completo y que correspondía trabajar; verifiqué que no fue un error de ponche.</label>}
    {!seleccion.revision?.liquidacionId&&<label className="block text-sm">Imagen de respaldo opcional (máximo 500 KB)<input type="file" className="block w-full min-w-0 max-w-full text-xs" accept="image/jpeg,image/png,image/webp" disabled={ocupado} onChange={e=>void adjuntar(e.target.files?.[0])}/></label>}
    {imagen&&<p className="text-sm">Imagen preparada para guardar.</p>}
    {seleccion.revision?.conImagen&&<button className="min-h-11 underline" onClick={async()=>{try{const r=await equipoApi<{imagen:string}>(`/api/asistencia?imagen=${encodeURIComponent(seleccion.id)}`);setVerImagen(r.imagen);}catch(e){setError((e as Error).message);}}}>Ver imagen privada</button>}{verImagen&&<img src={verImagen} alt="Respaldo privado de la revisión" className="max-h-80 max-w-full"/>}
    <div className="flex flex-wrap gap-2">{!seleccion.revision?.liquidacionId&&<><button disabled={ocupado||!motivo.trim()||!['tardanza','sin_ponche'].includes(seleccion.tipo)||(seleccion.tipo==='sin_ponche'&&!falta)} className="min-h-11 rounded bg-blue-700 text-white px-3 disabled:opacity-50" onClick={()=>void guardar('aprobar')}>Aprobar propuesta</button><button disabled={ocupado||!motivo.trim()} className="min-h-11 border rounded px-3 disabled:opacity-50" onClick={()=>void guardar('excusar')}>Excusar día</button><button disabled={ocupado||!motivo.trim()} className="min-h-11 border rounded px-3 disabled:opacity-50" onClick={()=>void guardar('descartar')}>Descartar descuento</button></>}<button disabled={ocupado} className="min-h-11 px-3" onClick={()=>{setSeleccion(null);setVerImagen('');}}>Cerrar revisión</button></div>
   </div>}
   {liquidacionId&&<button disabled={ocupado||loading} className="min-h-11 rounded bg-blue-700 px-4 text-white disabled:opacity-50" onClick={async()=>{setOcupado(true);setError('');try{const r=await equipoApi<{aplicadas:number;omitidas:number}>('/api/asistencia',{accion:'aplicar',liquidacionId});setRecarga(v=>v+1);setMensaje(`${r.aplicadas} descuentos incorporados. ${r.omitidas ? `${r.omitidas} pendientes porque el empleado no figura en esta nómina.` : 'Repetir no duplica los importes.'}`);}catch(e){setError((e as Error).message);}finally{setOcupado(false);}}}>Aplicar aprobados a esta nómina</button>}
  </>}
 </section>;
}
